extends Node

signal cell_built(cell_id: int, cell_type: StringName)
signal cell_converted(cell_id: int, new_type: StringName)
signal cell_neighbors_changed(cell_ids: Array)
signal resources_changed(snapshot: Dictionary)
signal build_menu_opened(cell_id: int)
signal build_menu_closed()
signal build_failed(cell_id: int)
signal assignment_changed(cell_id: int, bee_id: int)
signal production_tick(cell_id: int, resource_id: StringName, amount: int)
signal bee_created(bee_id: int)
signal bees_changed(bees: Array)
signal harvest_started(id: StringName, end_time: float, bees: int)
signal harvest_tick(id: StringName, time_left: float, partials: Dictionary)
signal harvest_completed(id: StringName, success: bool)
signal gatherer_bees_available_changed(count: int)
signal queen_selected(queen_id: StringName, modifiers: Dictionary)
signal queen_fed(honey_amount: int, eggs_produced: int)
signal bee_traits_assigned(bee_id: int, traits: Array)
signal defense_meter_changed(value: int)
signal threat_warning_started(id: StringName, power: int, end_time: float)
signal threat_resolved(id: StringName, success: bool, power: int, defense: int)
signal threat_cooldown_started(seconds: int)
signal boss_warning_started(end_time: float)
signal boss_phase_started(phase: int, power: int)
signal boss_phase_resolved(phase: int, success: bool, power: int, defense: int)
signal game_over(reason: String)
