extends Node

signal cell_built(cell_id: int, cell_type: StringName)
signal cell_converted(cell_id: int, new_type: StringName)
signal resources_changed(snapshot: Dictionary)
signal build_menu_opened(cell_id: int)
signal build_menu_closed()
signal build_failed(cell_id: int)
signal assignment_changed(cell_id: int, bee_id: int)
signal production_tick(cell_id: int, resource_id: StringName, amount: int)
signal bee_created(bee_id: int)
signal bees_changed(bees: Array)
signal harvest_started(id: StringName, end_time: float, bees: int)
signal harvest_tick(id: StringName, time_left: float, partials: Dictionary)
signal harvest_completed(id: StringName, success: bool)
signal gatherer_bees_available_changed(count: int)
